spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    user:
#      name: user
#      password: 123456
#      roles: ADMIN,BOSS
    url: jdbc:mysql://localhost:3306/todo?connectionTimeZone=SERVER
    username: root
    password: 12as!@AS
  jpa:
    show-sql: on
    open-in-view: off
logging:
  level:
    org.springframework.security: trace


